steps:
- id: build
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/$REPO_NAME:latest
  - --tag
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --cache-from
  - gcr.io/$PROJECT_ID/$REPO_NAME:latest
  - --build-arg
  - BUILDKIT_INLINE_CACHE=1
  - .
- id: push
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
- id: config
  name: gcr.io/ai2-reviz/jsonnet
  args:
  - eval
  - --yaml-stream
  - --output-file
  - .skiff/webapp.yaml
  - --tla-str
  - image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --tla-str
  - env=$_ENV
  - --tla-str
  - sha=$COMMIT_SHA
  - --tla-str
  - cause="Automated Skiff Deploy SHA:$COMMIT_SHA BUILD:$BUILD_ID"
  - --tla-str
  - branch=$BRANCH_NAME
  - --tla-str
  - repo=$REPO_NAME
  - --tla-str
  - buildId=$BUILD_ID
  - .skiff/webapp.jsonnet
- id: deploy
  name: gcr.io/ai2-reviz/rudder
  args:
  - deploy
  - -f
  - .skiff/webapp.yaml
substitutions:
  _ENV: prod
images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
- gcr.io/$PROJECT_ID/$REPO_NAME:latest
artifacts:
  objects:
    location: gs://skiff-archive/$REPO_NAME/$_ENV/$BUILD_ID/$COMMIT_SHA
    paths:
    - .skiff/webapp.yaml
options:
  env:
  - DOCKER_BUILDKIT=1
  machineType: N1_HIGHCPU_8

