import * as React from 'react';
import { VarnishApp } from '@allenai/varnish2';
import shellacCss from './autoGeneratedShellacCss.md';

export default function Demo() {
  const formatedCss = () => {
    let indent = false;
    return shellacCss.split('\n').map((line: string) => {
      if (line.indexOf('}') > -1) {
        indent = false;
      }
      const splitLine = line.split(': ');
      const ret = (
        <div>
          {indent ? <span>&nbsp;&nbsp;&nbsp;&nbsp;</span> : null}
          {splitLine.length > 1 ? (
            <span>
              <strong>{splitLine[0]}: </strong>
              <span>{splitLine[1]}</span>
            </span>
          ) : (
            line
          )}
        </div>
      );
      if (line.indexOf('{') > -1) {
        indent = true;
      }
      return ret;
    });
  };
  return (
    <VarnishApp>
      <div style={{ width: '100%', wordBreak: 'break-word' }}>{formatedCss()}</div>
    </VarnishApp>
  );
}
